/* Generated by cbindgen — do not edit. Regenerate: scripts/gen-header.sh */

#ifndef FUNPUT_H
#define FUNPUT_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Max output codepoints carried inline. Generous enough for English-restore of
 * long words; longer output is truncated (practically never happens).
 */
#define CHARS_CAP 64

/**
 * Platform action: `0 = None`, `1 = Send`, `2 = Restore`.
 */
#define ACTION_NONE 0

#define ACTION_SEND 1

#define ACTION_RESTORE 2

/**
 * Opaque IME engine handle for C callers. Create with [`funput_engine_new`],
 * release with [`funput_engine_free`]. cbindgen emits this as an opaque struct.
 */
typedef struct FunputEngine FunputEngine;

/**
 * Result of one keystroke, returned by value (POD, no allocation, no free).
 *
 * `chars[0..count]` are the output codepoints (UTF-32) to inject after deleting
 * `backspace` characters. For `action == ACTION_NONE`, `count == 0`.
 */
typedef struct {
    uint8_t action;
    uint32_t backspace;
    uint32_t count;
    uint32_t chars[CHARS_CAP];
} FunputResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new engine. Release it with [`funput_engine_free`].
 */
FunputEngine *funput_engine_new(void);

/**
 * Free an engine created by [`funput_engine_new`]. Null is ignored.
 *
 * # Safety
 * `engine` must come from [`funput_engine_new`] and not be freed already.
 */
void funput_engine_free(FunputEngine *engine);

/**
 * Set the input method: `0 = Telex`, `1 = VNI` (any other value = Telex).
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_method(FunputEngine *engine, uint8_t method);

/**
 * Set the tone-mark placement style: `0 = Traditional` (`hòa`), `1 = Modern`
 * (`hoà`) — any other value = Traditional.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_tone_style(FunputEngine *engine, uint8_t style);

/**
 * Enable or disable Vietnamese composition.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_enabled(FunputEngine *engine, bool enabled);

/**
 * Toggle auto-restore of non-Vietnamese words to their raw Latin keystrokes
 * (`card` stays `card`). When off, the composed buffer is always kept.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_smart_restore(FunputEngine *engine, bool on);

/**
 * Toggle eager restore — flip to raw keys the instant a word dead-ends instead of
 * waiting for a word boundary. Only applies while smart restore is on.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_eager_restore(FunputEngine *engine, bool on);

/**
 * Toggle spell-check ("Kiểm tra chính tả") — only place a diacritic when the result
 * can still become a real Vietnamese syllable, otherwise keep the modifier key as a
 * literal. Off by default.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_spell_check(FunputEngine *engine, bool on);

/**
 * Toggle auto-capitalize ("Tự động viết hoa") — uppercase the first letter of a word
 * that starts a sentence. Off by default; a no-op while off.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_set_auto_capitalize(FunputEngine *engine, bool on);

/**
 * Arm capitalization for the next word — call on text-field focus so the first
 * letter typed (start of input) is capitalized. A no-op unless auto-capitalize is on.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_arm_capitalization(FunputEngine *engine);

/**
 * Reset composition state (buffer + raw keys), e.g. on focus change.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_clear(FunputEngine *engine);

/**
 * Process one Unicode scalar. Returns the platform instruction by value.
 *
 * A null handle or invalid `codepoint` yields [`FunputResult::none`].
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
FunputResult funput_process_char(FunputEngine *engine, uint32_t codepoint);

/**
 * Copy the current composed buffer (the text the host shows as marked/underlined
 * composition) as UTF-32 into `out`, up to `cap` codepoints. Returns the number
 * of codepoints written.
 *
 * Null-safe: a null handle or null `out` yields `0`.
 *
 * # Safety
 * `engine` must be a valid handle or null. `out` must point to writable storage
 * for at least `cap` `u32` values, or be null.
 */
uintptr_t funput_buffer(const FunputEngine *engine, uint32_t *out, uintptr_t cap);

/**
 * Define a text-expansion shortcut (gõ tắt): typing `trigger` then a word boundary
 * injects `expansion` (`vn` → `Việt Nam`). Both strings are passed as UTF-32
 * (`*const u32` + length), matching [`funput_buffer`]. An empty trigger is ignored
 * by the engine; re-adding a trigger overwrites it.
 *
 * Hosts sync the whole table by calling [`funput_clear_shortcuts`] then adding each
 * entry (the engine is a runtime mirror of the host's config).
 *
 * Null-safe: a null handle does nothing. A null `trigger`/`expansion` pointer is
 * treated as an empty string.
 *
 * # Safety
 * `engine` must be a valid handle or null. `trigger` must point to at least
 * `trigger_len` `u32` values (or be null), and `expansion` to at least
 * `expansion_len` `u32` values (or be null).
 */
void funput_add_shortcut(FunputEngine *engine,
                         const uint32_t *trigger,
                         uintptr_t trigger_len,
                         const uint32_t *expansion,
                         uintptr_t expansion_len);

/**
 * Remove every text-expansion shortcut. Combine with [`funput_add_shortcut`] to
 * replace the whole table when syncing from config.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
void funput_clear_shortcuts(FunputEngine *engine);

/**
 * Backspace inside the current composition: drop the last composed character so
 * the next keystroke composes against the corrected text (`Phua` ⌫ `s` → `Phú`).
 *
 * Returns a no-op result — the host passes the Backspace through to delete one
 * character in the app.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
FunputResult funput_backspace(FunputEngine *engine);

/**
 * Flip the word being composed between its Vietnamese form and its raw keystrokes
 * (`card` ⇄ `cải`), and back on a second call. Returns the delete+inject the host
 * should apply (`ACTION_SEND`), or [`FunputResult::none`] when there is nothing to
 * flip. Hosts that show marked text can ignore the payload and re-render
 * [`funput_buffer`] after a non-`ACTION_NONE` result.
 *
 * # Safety
 * `engine` must be a valid handle or null.
 */
FunputResult funput_flip_composing(FunputEngine *engine);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FUNPUT_H */
