// RAII C++ wrapper around the `funput-ffi` C ABI (crates/funput-ffi/include/funput.h).
// Mirrors macOS's FunputComposer.swift: owns one opaque `FunputEngine*`, feeds it
// UTF-32 scalars, and decodes the composed buffer back to UTF-8 for Fcitx5.

#ifndef FUNPUT_FFI_HANDLE_H
#define FUNPUT_FFI_HANDLE_H

#include <cstdint>
#include <string>
#include <vector>

#include "funput.h" // generated by cbindgen; on the include path via CMake

namespace funput {

// Decode a UTF-8 string into Unicode scalars (the inverse of appendUtf8). Invalid
// bytes are skipped. Used to marshal gõ tắt strings to the FFI's uint32_t arrays.
inline std::vector<uint32_t> decodeUtf8(const std::string &s) {
    std::vector<uint32_t> out;
    size_t i = 0;
    const size_t n = s.size();
    while (i < n) {
        const auto b0 = static_cast<unsigned char>(s[i]);
        uint32_t cp = 0;
        size_t extra = 0;
        if (b0 < 0x80) {
            cp = b0;
        } else if ((b0 & 0xE0) == 0xC0) {
            cp = b0 & 0x1F;
            extra = 1;
        } else if ((b0 & 0xF0) == 0xE0) {
            cp = b0 & 0x0F;
            extra = 2;
        } else if ((b0 & 0xF8) == 0xF0) {
            cp = b0 & 0x07;
            extra = 3;
        } else {
            ++i; // invalid lead byte — skip
            continue;
        }
        if (i + extra >= n) break; // truncated sequence
        bool ok = true;
        for (size_t k = 1; k <= extra; ++k) {
            const auto bk = static_cast<unsigned char>(s[i + k]);
            if ((bk & 0xC0) != 0x80) {
                ok = false;
                break;
            }
            cp = (cp << 6) | (bk & 0x3F);
        }
        if (ok) {
            out.push_back(cp);
            i += extra + 1;
        } else {
            ++i; // malformed continuation — skip the lead byte
        }
    }
    return out;
}

// Append one Unicode scalar to a UTF-8 string.
inline void appendUtf8(std::string &out, uint32_t cp) {
    if (cp < 0x80) {
        out.push_back(static_cast<char>(cp));
    } else if (cp < 0x800) {
        out.push_back(static_cast<char>(0xC0 | (cp >> 6)));
        out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
    } else if (cp < 0x10000) {
        out.push_back(static_cast<char>(0xE0 | (cp >> 12)));
        out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
        out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
    } else {
        out.push_back(static_cast<char>(0xF0 | (cp >> 18)));
        out.push_back(static_cast<char>(0x80 | ((cp >> 12) & 0x3F)));
        out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
        out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
    }
}

// Owns the engine handle; non-copyable, movable.
class Handle {
public:
    Handle() : engine_(funput_engine_new()) {}
    ~Handle() { funput_engine_free(engine_); }

    Handle(const Handle &) = delete;
    Handle &operator=(const Handle &) = delete;
    Handle(Handle &&o) noexcept : engine_(o.engine_) { o.engine_ = nullptr; }
    Handle &operator=(Handle &&o) noexcept {
        if (this != &o) {
            funput_engine_free(engine_);
            engine_ = o.engine_;
            o.engine_ = nullptr;
        }
        return *this;
    }

    void setMethod(uint8_t method) { funput_set_method(engine_, method); }
    void setToneStyle(uint8_t style) { funput_set_tone_style(engine_, style); }
    void setEnabled(bool on) { funput_set_enabled(engine_, on); }
    void setSmartRestore(bool on) { funput_set_smart_restore(engine_, on); }
    void setEagerRestore(bool on) { funput_set_eager_restore(engine_, on); }
    void setSpellCheck(bool on) { funput_set_spell_check(engine_, on); }
    void setAutoCapitalize(bool on) { funput_set_auto_capitalize(engine_, on); }
    void armCapitalization() { funput_arm_capitalization(engine_); }
    void clear() { funput_clear(engine_); }

    // Text-expansion shortcuts (gõ tắt). Replace the whole table by clearing then
    // re-adding each entry (the engine is a runtime mirror of settings.json).
    void clearShortcuts() { funput_clear_shortcuts(engine_); }
    void addShortcut(const std::string &trigger, const std::string &expansion) {
        const std::vector<uint32_t> t = decodeUtf8(trigger);
        const std::vector<uint32_t> e = decodeUtf8(expansion);
        funput_add_shortcut(engine_, t.data(), t.size(), e.data(), e.size());
    }

    FunputResult process(uint32_t codepoint) { return funput_process_char(engine_, codepoint); }
    FunputResult backspace() { return funput_backspace(engine_); }

    // The composed (marked/underlined) buffer as UTF-8.
    std::string buffer() const {
        uint32_t cps[CHARS_CAP];
        uintptr_t n = funput_buffer(engine_, cps, CHARS_CAP);
        std::string out;
        for (uintptr_t i = 0; i < n; ++i) appendUtf8(out, cps[i]);
        return out;
    }

    // Decode a FunputResult's output codepoints (chars[0..count]) to UTF-8.
    static std::string output(const FunputResult &r) {
        std::string out;
        for (uint32_t i = 0; i < r.count; ++i) appendUtf8(out, r.chars[i]);
        return out;
    }

private:
    FunputEngine *engine_;
};

} // namespace funput

#endif // FUNPUT_FFI_HANDLE_H
